import { Router, type Router as RouterType } from 'express';
import { authRoutes } from './auth.routes.js';
import { userRoutes } from './user.routes.js';
import { permissionRoutes } from './permission.routes.js';
import { integrationRoutes } from './integration.routes.js';
import { campaignRoutes } from './campaign.routes.js';
import { invoiceRoutes } from './invoice.routes.js';
import { clientRoutes } from './client.routes.js';
import { portalRoutes } from './portal.routes.js';
import { workflowRoutes } from './workflow.routes.js';
import { reportRoutes } from './report.routes.js';
import { notificationRoutes } from './notification.routes.js';
import { taskRoutes } from './task.routes.js';
import { staffRoutes } from './staff.routes.js';
import { sopRoutes } from './sop.routes.js';
import { agreementRoutes } from './agreement.routes.js';
import { leadbyteRoutes } from './leadbyte.routes.js';
import { adSpendRoutes } from './ad-spend.routes.js';
import { uploadRoutes } from './upload.routes.js';
import { creativeRoutes } from './creative.routes.js';
export const router: RouterType = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/permissions', permissionRoutes);
router.use('/integrations', integrationRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/clients', clientRoutes);
router.use('/portal', portalRoutes);
router.use('/workflows', workflowRoutes);
router.use('/reports', reportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/tasks', taskRoutes);
router.use('/hr', staffRoutes);
router.use('/sops', sopRoutes);
router.use('/', agreementRoutes);
router.use('/leadbyte', leadbyteRoutes);
router.use('/ad-spend', adSpendRoutes);
router.use('/uploads', uploadRoutes);
router.use('/', creativeRoutes);
